MyBlog/urls.py
from django.contrib import admin
from django.urls import path, include
#basic urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('logreg/', include('logreg.urls')),
]

logreg/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
#'logij' urls
app_name='logreg'
urlpatterns = [
    path('register/', views.regindex, name='regindex'),
    path('login/', views.logindex, name='logindex'),
    path('logout/', views.oust, name='oust'),
    path('profile/', views.profile, name='profile'),
    path('', views.kick, name='kick'),
    path('regart/', views.regart, name='regart'),
    path('seeart/<int:aid>', views.seeart, name='seeart'),
    path('seeart/comment/<int:aid>/<int:uid>', views.compost, name='compost'),
    path('seeart/like/<int:aid>/<int:uid>', views.like, name='like'),
    path('seeart/dislike/<int:aid>/<int:uid>', views.dislike, name='dislike'),
    path('feed/', views.feed, name='feed'),
    path('profile/delete/', views.delete, name='delete'),
    path('profile/delete/goodbye', views.delete_account, name='delete_account')
]

pages/urls.py
from django.urls import path

from . import views
#'pages' urls
urlpatterns = [
    path('', views.index, name='index'),
]

templates/pages/index.html
{% extends 'base.html' %}

{% block title %}
<title>MyBlog Main</title>
{% endblock %}

{% block content %}
    <div class="card text-center">
        <div class="card-body">
            {% if messages %}
            {{message}}
            {% endif %}

                <h1>Welcome to blogApp</h1>
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-success">{{message}}</div>
                    {% endfor %}
                {% endif %}
                <a class="btn btn-dark" href="{% url 'logreg:logindex' %}">
                    Log In
                </a>
                <a class="btn btn-dark" href="{% url 'logreg:regindex' %}">
                    Register
                </a>
                <a class="btn btn-dark" href="admin/">
                    Admin
                </a>
        </div>
    </div>
{% endblock %}